name:                aoc2020
version:             0.1.0.0
github:              "sroccaserra/aoc2020"
license:             BSD3
author:              "Sébastien Roccaserra"
maintainer:          "sroccaserra"
copyright:           "2020 Idontcare"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Some ramblings around advent of code 2020
# category:            Code

description:         Please see the README on GitHub at <https://github.com/sroccaserra/aoc2020#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - hspec >= 2.7.4 && < 3
